// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Architecture',
      link: { type: 'doc', id: 'architecture-index' },
      items: ['ARCHITECTURE_AND_SECURITY', 'ARCHITECTURE'],
    },
    {
      type: 'category',
      label: 'SMP in C',
      link: { type: 'doc', id: 'smp-in-c-index' },
      items: ['CRYPTO', 'PROTOCOL', 'WIRE_FORMAT'],
    },
    {
      type: 'category',
      label: 'Protocol Analysis',
      link: { type: 'doc', id: 'protocol-analysis-index' },
      items: [
        { type: 'autogenerated', dirName: 'protocol-analysis' },
      ],
    },
    {
      type: 'category',
      label: 'Hardware',
      link: { type: 'doc', id: 'hardware-index' },
      items: [
        { type: 'autogenerated', dirName: 'hardware' },
        'ADDING_NEW_DEVICE',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      link: { type: 'doc', id: 'security-index' },
      items: ['SECURITY_MODEL'],
    },
    {
      type: 'category',
      label: 'Why SimpleGo',
      items: ['SIMPLEGO_VS_GRAPHENEOS', 'SIMPLEX_VS_MATRIX'],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: ['BUILD_SYSTEM', 'DEVELOPMENT', 'DEVNOTES'],
    },
    {
      type: 'category',
      label: 'Reference',
      link: { type: 'doc', id: 'constants' },
      items: ['TECHNICAL', 'BUGS', { type: 'autogenerated', dirName: 'release-info' }],
    },
  ],
};

export default sidebars;
